language: c++
compiler:
#  - clang
  - gcc

sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

before_install:
  - if [ "$CC"  == "gcc" ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++" ]; then export CXX=g++-5; fi

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX="$(pwd)/install"
  - cmake --build . --target install
  - ctest -VV
